<?php
/**
 * TL_ROOT/system/modules/tags/languages/cs/modules.php 
 * 
 * Contao extension: tags 1.7.0 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['tagcloud']['0'] = "Tag Cloud";
$GLOBALS['TL_LANG']['FMD']['tagcloud']['1'] = "Tento modul zobrazuje Tag Cloud.";
$GLOBALS['TL_LANG']['FMD']['globalArticleList']['0'] = "Tagy (Globální zeznam článků)";
$GLOBALS['TL_LANG']['FMD']['globalArticleList']['1'] = "Tento modul zobrazuje seznam článků s tagy z celé instalace Contao.";
$GLOBALS['TL_LANG']['FMD']['tagcontentlist']['0'] = "Tagy (Seznamu objektů)";
$GLOBALS['TL_LANG']['FMD']['tagcontentlist']['1'] = "Tento modul zobrazuje seznam objektů, které obsahují daný tagy.";
 
?>
