<?php
/**
 * TL_ROOT/system/modules/auto_completer/languages/nl/modules.php 
 * 
 * Contao extension: auto_completer 1.7.0 stable 
 * Niederländisch translation file 
 * 
 * Copyright : 2009 by Leo Unglaub && Christian Schiffler 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Leo Unglaub (leo.unglaub), http://www.leo-unglaub.net 
 * Translator: peter hamers (p.hamers) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['auto_completer']['0'] = "Auto Completer Zoek Module";
$GLOBALS['TL_LANG']['FMD']['auto_completer']['1'] = "Voegt een zoekvak toe met ajax-trefwoorden";
 
?>
