<?php
/**
 * TL_ROOT/system/modules/auto_completer/languages/nl/tl_module.php 
 * 
 * Contao extension: auto_completer 1.7.0 stable 
 * Niederländisch translation file 
 * 
 * Copyright : 2009 by Leo Unglaub && Christian Schiffler 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Leo Unglaub (leo.unglaub), http://www.leo-unglaub.net 
 * Translator: peter hamers (p.hamers) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['ajax_legend'] = "Auto Completer - Configuratie";
$GLOBALS['TL_LANG']['tl_module']['use_auto_completer']['0'] = "Inschakelen Auto-Completer";
$GLOBALS['TL_LANG']['tl_module']['use_auto_completer']['1'] = "Schakel de Auto-Completer Uitbreiding in op deze module (trefwoord suggestie zoals bekend van Google of Wikipedia";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_override_global']['0'] = "Overschrijf globale instellingen";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_override_global']['1'] = "Overschrijf de instellingen zoals gemaakt in de globale contao instellingen.";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_expert_settings']['0'] = "expert opties";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_expert_settings']['1'] = "Toon de expert opties.Deze opties zijn alleen voor gevorderde gebruikers.";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_min_length']['0'] = "min lengte";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_min_length']['1'] = "(Integer) de minimale lengte van de string welke de gebruiker moet invoeren voordat de suggesties worden weergegeven; standaard ingesteld op 1";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_max_choises']['0'] = "max keuzes";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_max_choises']['1'] = "(Integer) het maximale aantal suggestie om te laten zien; standaard op 10.";
$GLOBALS['TL_LANG']['tl_module']['auto_complete_ignore_words']['0'] = "negeerlijst";
$GLOBALS['TL_LANG']['tl_module']['auto_complete_ignore_words']['1'] = "U kunt een lijst met komma gescheiden waarden invoegen om deze uit te sluiten van het zoekresultaat.";
$GLOBALS['TL_LANG']['tl_module']['auto_complete_template']['0'] = "Template";
$GLOBALS['TL_LANG']['tl_module']['auto_complete_template']['1'] = "Selecteer een template welke gebruikt zal worden voor weergave van de box.";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_mark_query']['0'] = "markeer zoekopdracht";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_width']['0'] = "breedte";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_width']['1'] = "(Gemengd) hetzij de string 'overerven', waarin wordt bepaald dat de voorgestelde dropdown net zo breed moet zijn als de input, of een integer voor de gewenste breedte in pixels; standaarden tot 'overerven'";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_inject_choice']['0'] = "keuze maken";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_custom_choices']['0'] = "aangepaste_keuzes";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_class_name']['0'] = "class naam";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_z_index']['0'] = "z-index";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_delay']['0'] = "vertraagd";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_select_first']['0'] = "selecteer eerste";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_filter']['0'] = "filter";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_filter_case']['0'] = "filter case";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_filter_subset']['0'] = "filter subset";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_force_select']['0'] = "Forceer selectie";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_select_mode']['0'] = "Selecteer mode";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_cache']['0'] = "cache";
$GLOBALS['TL_LANG']['tl_module']['auto_completer_relative']['0'] = "relatief";
 
?>
