<?php
/**
 * TL_ROOT/system/modules/auto_completer/languages/nl/tl_settings.php 
 * 
 * Contao extension: auto_completer 1.7.0 stable 
 * Niederländisch translation file 
 * 
 * Copyright : 2009 by Leo Unglaub && Christian Schiffler 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Leo Unglaub (leo.unglaub), http://www.leo-unglaub.net 
 * Translator: peter hamers (p.hamers) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['use_auto_completer']['0'] = "Aanzetten Auto-Completer";
$GLOBALS['TL_LANG']['tl_settings']['auto_completer_class_name']['0'] = "class naam";
$GLOBALS['TL_LANG']['tl_settings']['auto_completer_z_index']['0'] = "z-index";
$GLOBALS['TL_LANG']['tl_settings']['auto_completer_separator']['0'] = "Scheidingsteken";
$GLOBALS['TL_LANG']['tl_settings']['auto_completer_separator_split']['0'] = "Scheidingsteken delen";
$GLOBALS['TL_LANG']['tl_settings']['auto_completer_auto_trim']['0'] = "Auto Trim";
$GLOBALS['TL_LANG']['tl_settings']['auto_completer_cache']['0'] = "cache";
$GLOBALS['TL_LANG']['tl_settings']['auto_completer_relative']['0'] = "relatief";
$GLOBALS['TL_LANG']['tl_settings']['auto_completer_relative']['1'] = "(boolean) als waar, het suggestie dropdown-element wordt direct gebruikt na de input.Dit staat toe dat de ouder van de input verschuift en dat de suggestie dropdown hierin meegaat;standaard onwaar.";
 
?>
