<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/ru/modules.php 
 * 
 * Contao extension: BackupDB 1.2.0 stable 
 * Russian translation file 
 * 
 * Copyright : 2007-2010 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Hagen Klemp (do_while), http://www.softleister.de 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['BackupDB']['0'] = "Резервное копирование базы данных";
$GLOBALS['TL_LANG']['MOD']['BackupDB']['1'] = "Создать и загрузить резервную копию базы данных";
 
?>