<?php
/**
 * TL_ROOT/system/modules/myContaoSearchPortal/languages/de/tl_mcsp_categories.php 
 * 
 * TYPOlight extension: myContaoSearchPortal
 * Deutsch translation file 
 * 
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL 
 * Author    : Sven Rhinow, http://www.sr-tag.de/ 
 * Translator: Sven Rhinow (ScuM666) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_mcsp_categories']['title'] = "Kategorie";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['name']['0'] = "Name";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['name']['1'] = "Name der Kategorie.";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['alias']['1'] = "Alias, um auf die Bedingung verweisen zu können.";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['new']['0'] = "Neue Kategorie";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['new']['1'] = "Neue Kategorie erstellen.";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['show']['0'] = "Einzelheiten der Bedingung";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['show']['1'] = "Einzelheiten der Bedingung ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['edit']['0'] = "Kategorie bearbeiten";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['edit']['1'] = "Kategorie ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['copy']['0'] = "Kategorie kopieren";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['copy']['1'] = "Kategorie ID %s kopieren";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['cut']['0'] = "Begriff verschieben";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['cut']['1'] = "Begriff ID %s verschieben";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['delete']['0'] = "Kategorie löschen";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['delete']['1'] = "Kategorie ID %s löschen";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['copyChildren']['0'] = "Begriff mit Unterbegriffen kopieren";
$GLOBALS['TL_LANG']['tl_mcsp_categories']['copyChildren']['1'] = "Begriff ID %s mit Unterbegriffen kopieren";
 
?>
