<?php
/**
 * TL_ROOT/system/modules/myContaoSearchPortal/languages/de/tl_mcsp_smallads.php 
 * 
 * TYPOlight extension: myContaoSearchPortal
 * Deutsch translation file 
 * 
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL 
 * Author    : Sven Rhinow, http://www.sr-tag.de/ 
 * Translator: Sven Rhinow (ScuM666) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['title'] = array('Name','Name des Angebotes.');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['description'] = array('Anzeigen-Beschreibung','');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['alias'] = array('Alias','Alias, um auf die Bedingung verweisen zu können.');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['userid'] = array('Anzeigen-Besitzer','');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['typeid'] = array('Anzeigen-Typ','');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['stateid'] = array('Status','');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['is_picture'] = array('Bilder vorhanden/anzeigen','');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['is_link'] = array('Link anzeigen','');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['pictures'] = array('Bilder der Anzeige','');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['is_video'] = array('Video vorhanden/anzeigen','');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['is_hightlight'] = array('Anzeige hervorheben','die Anzeige wird grafisch von den anderen abgehoben.');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['is_title_hightlight'] = array('Titel hervorheben','');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['is_bg_hightlight'] = array('Hintergrund hervorheben','');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['view_type'] = array('Darstellung','Push-Up wird alle 5 Tage an den ersten Platz gesetzt als wen die Anzeige gerade erst eingestellt wurde. Premium wird mit "Top Angebot" und farblicher Hervorhebung an erster Stelle angezeigt.');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['categoryid'] = array('Kategorie','');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['video_title'] = array('Titel zum Videos','');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['int_videopath'] = array('interner Videopfad','');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['ext_videopath'] = array('externer Videopfad','es kann der embed-Code eingegeben werden. es wird automatisch der URL extrahiert.');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['ext_videoportal'] = array('Videoportal bei externer Videoquelle','');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['basic_agreement'] = array('Vereinbarungsbasis (VB)','wenn eine Verhandlung möglich sein soll');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['price'] = array('Preis','z.B. 20 oder 11,12 OHNE Währung');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['adid'] = array('Anzeigen-Nr.:','');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['zc_id'] = array('PLZ / Ort:','');

$GLOBALS['TL_LANG']['tl_mcsp_smallads']['new']  = array('Neues Angebote','Neues Angebote erstellen.');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['show'] = array('Einzelheiten der Bedingung','Einzelheiten der Bedingung ID %s anzeigen');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['edit'] = array('Angebot bearbeiten','Angebot ID %s bearbeiten');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['copy'] = array('Angebot kopieren','Angebot ID %s kopieren');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['cut'] = array('Begriff verschieben','Begriff ID %s verschieben');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['delete'] = array('Angebot löschen','Angebot ID %s löschen');
$GLOBALS['TL_LANG']['tl_mcsp_smallads']['copyChildren'] = array('Begriff mit Unterbegriffen kopieren','Begriff ID %s mit Unterbegriffen kopieren'); 

$GLOBALS['TL_LANG']['tl_mcsp_smallads']['options_legend'] = 'Anzeige-Optionen';
?>
