<?php
/**
 * TL_ROOT/system/modules/myContaoSearchPortal/languages/de/tl_mcsp_types.php 
 * 
 * TYPOlight extension: myContaoSearchPortal 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL 
 * Author    : Sven Rhinow, http://www.sr-tag.de/ 
 * Translator: Sven Rhinow (ScuM666) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_mcsp_types']['new']    = array('Neuer Anzeigentyp', 'Ein neuen Anzeigentyp anlegen');
$GLOBALS['TL_LANG']['tl_mcsp_types']['edit']   = array('Anzeigentyp bearbeiten', 'Anzeigentyp ID %s bearbeiten');
$GLOBALS['TL_LANG']['tl_mcsp_types']['copy']   = array('Anzeigentyp duplizieren', 'Anzeigentyp ID %s duplizieren');
$GLOBALS['TL_LANG']['tl_mcsp_types']['delete'] = array('Anzeigentyp löschen', 'Anzeigentyp ID %s löschen');
$GLOBALS['TL_LANG']['tl_mcsp_types']['show']   = array('Anzeigentyp-Details', 'Details von dem Anzeigentyp ID %s anzeigen');

$GLOBALS['TL_LANG']['tl_mcsp_types']['name']   = array('Name des Types', '');
?>