<?php
/**
 * TL_ROOT/system/modules/taxonomy/languages/de/tl_taxonomy.php 
 * 
 * TYPOlight extension: taxonomy 0.1.6 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design (thyon, s.c.a.r.e) 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Joachim Scholtysik (jscholtysik) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_taxonomy']['title'] = "Taxonomie-Bedingungen";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['0'] = "Name";
$GLOBALS['TL_LANG']['tl_taxonomy']['name']['1'] = "Name der Bedingung.";
$GLOBALS['TL_LANG']['tl_taxonomy']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_taxonomy']['alias']['1'] = "Alias, um auf die Bedingung verweisen zu können.";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['0'] = "Neue Bedingung";
$GLOBALS['TL_LANG']['tl_taxonomy']['new']['1'] = "Neue Bedingung erstellen.";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['0'] = "Einzelheiten der Bedingung";
$GLOBALS['TL_LANG']['tl_taxonomy']['show']['1'] = "Einzelheiten der Bedingung ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['0'] = "Bedingung bearbeiten";
$GLOBALS['TL_LANG']['tl_taxonomy']['edit']['1'] = "Bedingung ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['0'] = "Bedingung kopieren";
$GLOBALS['TL_LANG']['tl_taxonomy']['copy']['1'] = "Bedingung ID %s kopieren";
$GLOBALS['TL_LANG']['tl_taxonomy']['cut']['0'] = "Begriff verschieben";
$GLOBALS['TL_LANG']['tl_taxonomy']['cut']['1'] = "Begriff ID %s verschieben";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['0'] = "Bedingung löschen";
$GLOBALS['TL_LANG']['tl_taxonomy']['delete']['1'] = "Bedingung ID %s löschen";
$GLOBALS['TL_LANG']['tl_taxonomy']['copyChildren']['0'] = "Begriff mit Unterbegriffen kopieren";
$GLOBALS['TL_LANG']['tl_taxonomy']['copyChildren']['1'] = "Begriff ID %s mit Unterbegriffen kopieren";
 
?>
